[package]
name = "timber"
version = "0.1.0"
authors = ["lerina <icode.lerina@gmail.com>"]
keywords = ["sfml", "multimedia", "game"]

[dependencies]
sfml = "0.12"
rand = "0.3"
conv = "0.3"
#nphysics2d = "0.6"
